In [1]:
from pathlib import Path
import getpass
import os
import shutil

import numpy as np
import pandas as pd
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

/var/folders/jm/7clyqzg57313wr8rz15hptym0000gn/T/ipykernel_21130/2993139619.py:8: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader

In [2]:
if not os.environ.get("OPENAI_API_KEY"):
    os.environ["OPENAI_API_KEY"] = getpass.getpass(
        "Enter your OpenAI API key: "
    )

print("OpenAI API key configured successfully.")

OpenAI API key configured successfully.

In [3]:
DATA_DIR = Path(
    r"/Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data")

preferred_pdf = DATA_DIR / "llama2-research-paper.pdf"

if preferred_pdf.exists():
    PDF_PATH = preferred_pdf
else:
    # Automatically find the PDF if its filename is slightly different
    available_pdfs = sorted(DATA_DIR.glob("*.pdf"))

    if len(available_pdfs) == 1:
        PDF_PATH = available_pdfs[0]
    elif len(available_pdfs) == 0:
        raise FileNotFoundError(
            f"No PDF file was found inside:\n{DATA_DIR}"
        )
    else:
        raise RuntimeError(
            "Multiple PDF files were found. Please set PDF_PATH manually.\n"
            + "\n".join(str(path) for path in available_pdfs)
        )

print("PDF found:")
print(PDF_PATH)

PDF found:
/Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf

In [4]:
loader = PyPDFLoader(str(PDF_PATH))
pages = loader.load()
print(f"Total PDF pages loaded: {len(pages)}")

Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.

Total PDF pages loaded: 77

In [5]:
print("First-page metadata:")
print(pages[0].metadata)

print("\nFirst 1,000 characters:")
print(pages[0].page_content[:1000])

First-page metadata:
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': '/Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1'}

First 1,000 characters:
Llama 2: Open Foundation and Fine-Tuned Chat Models
Hugo Touvron∗ Louis Martin† Kevin Stone†
Peter Albert Amjad Almahairi Yasmine Babaei Nikolay Bashlykov Soumya Batra
Prajjwal Bhargava Shruti Bhosale Dan Bikel Lukas Blecher Cristian Canton Ferrer Moya Chen
Guillem Cucurull David Esiobu Jude Fernandes Jeremy Fu Wenyin Fu Brian Fuller
Cynthia Gao Vedanuj Goswami Naman Goyal Anthony Hartshorn Saghar Hosseini Rui Hou
Hakan Inan Marcin Kardas Viktor Kerkez Madian Khabsa Isabel Kloumann Artem Korenev
Punit Singh Koura Marie-Anne Lachaux Thibaut Lavril Jenya Lee Diana Liskovich
Yinghai Lu Yuning Mao Xavier Martinet Todor Mihaylov Pushkar Mishra
Igor Molybog Yixin Nie Andrew Poulton Jeremy Reizenstein Rashi Rungta Kalyan Saladi
Alan Schelten Ruan Silva Eric Michael Smith Ranjan Subramanian Xiaoqing Ellen Tan Binh Tang
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic
Sergey Edunov

In [6]:
def identify_section(paper_page: int) -> str:
    """
    Identify the major section of the Llama 2 paper
    using its printed PDF page number.
    """

    if 1 <= paper_page <= 2:
        return "front_matter"

    if 3 <= paper_page <= 4:
        return "introduction"

    if 5 <= paper_page <= 7:
        return "pretraining"

    if 8 <= paper_page <= 19:
        return "fine_tuning"

    if 20 <= paper_page <= 31:
        return "safety"

    if 32 <= paper_page <= 35:
        return "discussion"

    if paper_page == 36:
        return "conclusion"

    if 37 <= paper_page <= 45:
        return "references"

    if 46 <= paper_page <= 77:
        return "appendix"

    return "unknown"

In [7]:
for page_document in pages:
    # PyPDFLoader page index is normally zero-based
    page_index = int(page_document.metadata.get("page", 0))
    paper_page = page_index + 1

    page_document.metadata.update(
        {
            "paper": "Llama 2",
            "organization": "Meta",
            "year": 2023,
            "document_type": "research_paper",
            "paper_page": paper_page,
            "section": identify_section(paper_page),
            "access_level": "public",
        }
    )

In [8]:
for page_document in pages[:5]:
    print(page_document.metadata)

{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': '/Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 1, 'section': 'front_matter', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': '/Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf', 'total_pages': 77, 'page': 1, 'page_label': '2', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 2, 'section': 'front_matter', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': '/Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf', 'total_pages': 77, 'page': 2, 'page_label': '3', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 3, 'section': 'introduction', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': '/Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf', 'total_pages': 77, 'page': 3, 'page_label': '4', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 4, 'section': 'introduction', 'access_level': 'public'}
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': '/Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf', 'total_pages': 77, 'page': 4, 'page_label': '5', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 5, 'section': 'pretraining', 'access_level': 'public'}

In [9]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    add_start_index=True,
)

chunks = text_splitter.split_documents(pages)

print(f"Total pages: {len(pages)}")
print(f"Total chunks: {len(chunks)}")

Total pages: 77
Total chunks: 343

In [10]:
print("Chunk content:")
print(chunks[0].page_content[:1000])

print("\nChunk metadata:")
print(chunks[0].metadata)

Chunk content:
Llama 2: Open Foundation and Fine-Tuned Chat Models
Hugo Touvron∗ Louis Martin† Kevin Stone†
Peter Albert Amjad Almahairi Yasmine Babaei Nikolay Bashlykov Soumya Batra
Prajjwal Bhargava Shruti Bhosale Dan Bikel Lukas Blecher Cristian Canton Ferrer Moya Chen
Guillem Cucurull David Esiobu Jude Fernandes Jeremy Fu Wenyin Fu Brian Fuller
Cynthia Gao Vedanuj Goswami Naman Goyal Anthony Hartshorn Saghar Hosseini Rui Hou
Hakan Inan Marcin Kardas Viktor Kerkez Madian Khabsa Isabel Kloumann Artem Korenev
Punit Singh Koura Marie-Anne Lachaux Thibaut Lavril Jenya Lee Diana Liskovich
Yinghai Lu Yuning Mao Xavier Martinet Todor Mihaylov Pushkar Mishra
Igor Molybog Yixin Nie Andrew Poulton Jeremy Reizenstein Rashi Rungta Kalyan Saladi
Alan Schelten Ruan Silva Eric Michael Smith Ranjan Subramanian Xiaoqing Ellen Tan Binh Tang
Ross Taylor Adina Williams Jian Xiang Kuan Puxin Xu Zheng Yan Iliyan Zarov Yuchen Zhang
Angela Fan Melanie Kambadur Sharan Narang Aurelien Rodriguez Robert Stojnic

Chunk metadata:
{'producer': 'pdfTeX-1.40.25', 'creator': 'LaTeX with hyperref', 'creationdate': '2023-07-20T00:30:36+00:00', 'author': '', 'keywords': '', 'moddate': '2023-07-20T00:30:36+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) kpathsea version 6.3.5', 'subject': '', 'title': '', 'trapped': '/False', 'source': '/Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf', 'total_pages': 77, 'page': 0, 'page_label': '1', 'paper': 'Llama 2', 'organization': 'Meta', 'year': 2023, 'document_type': 'research_paper', 'paper_page': 1, 'section': 'front_matter', 'access_level': 'public', 'start_index': 0}

In [11]:
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small"
)

In [12]:
test_vector = embeddings.embed_query(
    "What is Llama 2?"
)

print(f"Embedding dimensions: {len(test_vector)}")
print(f"First 10 values: {test_vector[:10]}")

Embedding dimensions: 1536
First 10 values: [0.0028285980224609375, -0.052093505859375, -0.0210418701171875, -0.05535888671875, -0.0264129638671875, 0.028961181640625, -0.0020694732666015625, 0.03472900390625, -0.0164794921875, -0.02447509765625]

In [13]:
PERSIST_DIRECTORY = DATA_DIR / "chroma_llama2_retriever"

# Set this to False when you want to reuse the existing index.
REBUILD_INDEX = True

if REBUILD_INDEX and PERSIST_DIRECTORY.exists():
    shutil.rmtree(
        PERSIST_DIRECTORY,
        ignore_errors=True
    )

In [14]:
PERSIST_DIRECTORY = Path.home() / ".chroma" / "chroma_llama2_retriever"
PERSIST_DIRECTORY.mkdir(parents=True, exist_ok=True)

vector_store = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    collection_name="llama2_retriever_demo",
    persist_directory=str(PERSIST_DIRECTORY),
    collection_configuration={"hnsw": {"space": "cosine"}},
)

print("Vector store created successfully.")
print(f"Stored chunks: {len(chunks)}")
print(f"Persisted at: {PERSIST_DIRECTORY}")

Vector store created successfully.
Stored chunks: 343
Persisted at: /Users/sainaveenvasa/.chroma/chroma_llama2_retriever

In [15]:
PERSIST_DIRECTORY = DATA_DIR / "chroma_llama2_retriever"

In [16]:
PERSIST_DIRECTORY

PosixPath('/Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/chroma_llama2_retriever')

In [17]:
# Load the existing Chroma collection
vector_store = Chroma(
    collection_name="llama2_retriever_demo",
    embedding_function=embeddings,
    persist_directory=str(PERSIST_DIRECTORY),
)

print("Existing vector store loaded successfully.")
print(f"Persist directory: {PERSIST_DIRECTORY}")

Existing vector store loaded successfully.
Persist directory: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/chroma_llama2_retriever

In [18]:
def display_documents(
    documents,
    max_characters: int = 700
) -> None:
    """
    Display retrieved LangChain Document objects clearly.
    """

    if not documents:
        print("No documents were returned.")
        return

    for rank, document in enumerate(documents, start=1):
        metadata = document.metadata

        print("=" * 90)
        print(f"RANK: {rank}")
        print(f"PAPER PAGE: {metadata.get('paper_page')}")
        print(f"SECTION: {metadata.get('section')}")
        print(f"CHUNK ID: {metadata.get('chunk_id')}")
        print(f"SOURCE: {metadata.get('source')}")
        print("-" * 90)
        print(document.page_content[:max_characters])
        print()

In [19]:
# vector_store.similarity_search()

In [20]:
similarity_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4
    }
)

In [21]:
query = "What model sizes of Llama 2 were released?"

similarity_documents = similarity_retriever.invoke(query)
display_documents(similarity_documents)

No documents were returned.

In [22]:
mmr_retriever = vector_store.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 4,
        "fetch_k": 20,
        "lambda_mult": 0.5,
    }
)

In [23]:
query = "How was Llama 2-Chat trained and aligned?"
mmr_documents = mmr_retriever.invoke(query)

display_documents(mmr_documents)

No documents were returned.

In [24]:
query = "How was Llama 2-Chat trained and aligned?"

similarity_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 4}
)

mmr_retriever = vector_store.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 4,
        "fetch_k": 20,
        "lambda_mult": 0.5,
    }
)

similarity_results = similarity_retriever.invoke(query)
mmr_results = mmr_retriever.invoke(query)

In [25]:
print("Similarity Search results:")
for document in similarity_results:
    print(
        document.metadata.get("paper_page"),
        document.metadata.get("section"),
        document.metadata.get("chunk_id"),
    )

print("\nMMR results:")
for document in mmr_results:
    print(
        document.metadata.get("paper_page"),
        document.metadata.get("section"),
        document.metadata.get("chunk_id"),
    )

Similarity Search results:

MMR results:

In [26]:
threshold_retriever = vector_store.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={
        "k": 10,
        "score_threshold": 0.64
    }
)

In [27]:
query = "What safety techniques were used for Llama 2-Chat?"
threshold_documents = threshold_retriever.invoke(query)
display_documents(threshold_documents)

No relevant docs were retrieved using the relevance score threshold 0.64

No documents were returned.

similarity_score_threshold is a LangChain search type that returns only documents whose similarity score meets a specified minimum threshold.

In [28]:
query = "What safety techniques were used for Llama 2-Chat?"

scored_results = vector_store.similarity_search_with_relevance_scores(
    query=query,
    k=5,
)

for rank, (document, relevance_score) in enumerate(
    scored_results,
    start=1
):
    print("=" * 90)
    print(f"Rank: {rank}")
    print(f"Relevance score: {relevance_score:.4f}")
    print(f"Paper page: {document.metadata.get('paper_page')}")
    print(f"Section: {document.metadata.get('section')}")
    print(document.page_content[:500])

In [29]:
metric_query = "How was reinforcement learning with human feedback used?"

candidate_documents = vector_store.similarity_search(
    metric_query,
    k=6,
)

candidate_texts = [
    document.page_content
    for document in candidate_documents
]

print(f"Candidate chunks selected: {len(candidate_texts)}")

Candidate chunks selected: 0

In [30]:
query_vector = np.asarray(
    embeddings.embed_query(metric_query),
    dtype=np.float64,
)

document_vectors = np.asarray(
    embeddings.embed_documents(candidate_texts),
    dtype=np.float64,
)

print("Query-vector shape:", query_vector.shape)
print("Document-vectors shape:", document_vectors.shape)

Query-vector shape: (1536,)
Document-vectors shape: (0,)

In [31]:
def cosine_similarity(
    vector_a: np.ndarray,
    vector_b: np.ndarray
) -> float:
    denominator = (
        np.linalg.norm(vector_a)
        * np.linalg.norm(vector_b)
    )

    if denominator == 0:
        return 0.0

    return float(
        np.dot(vector_a, vector_b) / denominator
    )


def euclidean_distance(
    vector_a: np.ndarray,
    vector_b: np.ndarray
) -> float:
    return float(
        np.linalg.norm(vector_a - vector_b)
    )


def dot_product(
    vector_a: np.ndarray,
    vector_b: np.ndarray
) -> float:
    return float(
        np.dot(vector_a, vector_b)
    )

In [32]:
metric_rows = []

for document, document_vector in zip(
    candidate_documents,
    document_vectors
):
    metric_rows.append(
        {
            "paper_page": document.metadata.get("paper_page"),
            "section": document.metadata.get("section"),
            "chunk_id": document.metadata.get("chunk_id"),
            "cosine_similarity": cosine_similarity(
                query_vector,
                document_vector
            ),
            "euclidean_distance": euclidean_distance(
                query_vector,
                document_vector
            ),
            "dot_product": dot_product(
                query_vector,
                document_vector
            ),
            "preview": document.page_content[:100].replace(
                "\n",
                " "
            ),
        }
    )

metric_table = pd.DataFrame(metric_rows)

metric_table

Empty DataFrame
Columns: []
Index: []

In [33]:
metric_query

'How was reinforcement learning with human feedback used?'

In [35]:
PERSIST_DIRECTORY = DATA_DIR / "chroma_llama2_retriever"
PERSIST_DIRECTORY.mkdir(parents=True, exist_ok=True)

vector_store = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    collection_name="llama2_retriever_demo",
    persist_directory=str(PERSIST_DIRECTORY),
    collection_configuration={"hnsw": {"space": "cosine"}},
)

In [37]:
# Rebuild metric_table if it is empty or missing the needed column.
if metric_table.empty or "euclidean_distance" not in metric_table.columns:
    metric_query = "How was reinforcement learning with human feedback used?"

    candidate_documents = vector_store.similarity_search(metric_query, k=6)
    candidate_texts = [document.page_content for document in candidate_documents]

    query_vector = np.asarray(
        embeddings.embed_query(metric_query),
        dtype=np.float64,
    )

    document_vectors = np.asarray(
        embeddings.embed_documents(candidate_texts),
        dtype=np.float64,
    )

    metric_rows = []

    for document, document_vector in zip(candidate_documents, document_vectors):
        metric_rows.append(
            {
                "paper_page": document.metadata.get("paper_page"),
                "section": document.metadata.get("section"),
                "chunk_id": document.metadata.get("chunk_id"),
                "cosine_similarity": cosine_similarity(
                    query_vector,
                    document_vector,
                ),
                "euclidean_distance": euclidean_distance(
                    query_vector,
                    document_vector,
                ),
                "dot_product": dot_product(
                    query_vector,
                    document_vector,
                ),
                "preview": document.page_content[:100].replace("\n", " "),
            }
        )

    metric_table = pd.DataFrame(metric_rows)

metric_table.sort_values(
    by="euclidean_distance",
    ascending=True
)[
    [
        "paper_page",
        "section",
        "euclidean_distance",
        "preview",
    ]
]

,paper_page,section,euclidean_distance,preview
0,9,fine_tuning,0.916081,"learning rate of2× 10−5, a weight decay of 0.1..."
1,32,discussion,0.960776,"bility, seemed a somewhat shadowy field for th..."
2,17,fine_tuning,0.971322,system message during the conversation by inte...
3,13,fine_tuning,0.995461,evaluating a generative model is an open resea...
4,10,fine_tuning,1.000081,"sampled human preferences, whereby human annot..."
5,10,fine_tuning,1.004014,3.2.2 Reward Modeling The reward model takes a...

In [38]:
metric_table.sort_values(
    by="dot_product",
    ascending=False
)[
    [
        "paper_page",
        "section",
        "dot_product",
        "preview",
    ]
]

,paper_page,section,dot_product,preview
0,9,fine_tuning,0.580113,"learning rate of2× 10−5, a weight decay of 0.1..."
1,32,discussion,0.538555,"bility, seemed a somewhat shadowy field for th..."
2,17,fine_tuning,0.528291,system message during the conversation by inte...
3,13,fine_tuning,0.504404,evaluating a generative model is an open resea...
4,10,fine_tuning,0.500330,"sampled human preferences, whereby human annot..."
5,10,fine_tuning,0.495783,3.2.2 Reward Modeling The reward model takes a...

In [39]:
normalized_query_vector = (
    query_vector / np.linalg.norm(query_vector)
)

normalized_document_vectors = (
    document_vectors
    / np.linalg.norm(
        document_vectors,
        axis=1,
        keepdims=True
    )
)

normalized_dot_scores = (
    normalized_document_vectors
    @ normalized_query_vector
)

cosine_scores = np.asarray(
    [
        cosine_similarity(
            query_vector,
            document_vector
        )
        for document_vector in document_vectors
    ]
)

print("Cosine scores:")
print(cosine_scores)

print("\nDot product after normalization:")
print(normalized_dot_scores)

print(
    "\nAre they approximately equal?",
    np.allclose(
        cosine_scores,
        normalized_dot_scores,
        atol=1e-8,
    ),
)

Cosine scores:
[0.58027849 0.53850125 0.52827828 0.50446663 0.50012423 0.4958799 ]

Dot product after normalization:
[0.58027849 0.53850125 0.52827828 0.50446663 0.50012423 0.4958799 ]

Are they approximately equal? True

In [40]:
fine_tuning_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": {
            "section": "fine_tuning"
        },
    }
)

In [41]:
query = "How was Llama 2-Chat aligned with human preferences?"

fine_tuning_documents = fine_tuning_retriever.invoke(query)

display_documents(fine_tuning_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 19
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Figure12: Humanevaluationresults for Llama 2-Chatmodelscomparedtoopen-andclosed-sourcemodels
across ~4,000 helpfulness prompts with three raters per prompt.
The largestLlama 2-Chat model is competitive with ChatGPT.Llama 2-Chat 70B model has a win rate of
36% and a tie rate of 31.5% relative to ChatGPT.Llama 2-Chat 70B model outperforms PaLM-bison chat
model by a large percentage on our prompt set. More results and analysis is available in Section A.3.7.
Inter-Rater Reliability (IRR). In our human evaluations, three different annotators provided independent
assessments for each model generation comparison. High IRR scores (closer to 1.0) are typically seen as
better from a data quality persp

==========================================================================================
RANK: 2
PAPER PAGE: 18
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
biased in favor ofLlama 2-Chat. Therefore, for a fair comparison, we additionally compute the final results
usingGPT-4toassesswhichgenerationispreferred. TheorderinwhichChatGPTand Llama 2-Chatoutputs
appeared in GPT-4 prompt are randomly swapped to avoid any bias. As expected, the win-rate in favor of
Llama 2-Chat is less pronounced, although obtaining more than a 60% win-rate for our latestLlama 2-Chat.
The prompts correspond to a validation set of1, 586and 584prompts for safety and helpfulness, respectively.
3.4.2 Human Evaluation
Human evaluation is often considered the gold standard for judging models for natural language generation,
including dialogue models. To evaluate the quality of

==========================================================================================
RANK: 3
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
can be found in Section 4.2.1.
Human annotations were collected in batches on a weekly basis. As we collected more preference data, our
reward models improved, and we were able to train progressively better versions forLlama 2-Chat (see
the results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.
Since reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from
hyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to
gather new preference data using the latestLlama 2-Chat iterations. This step helps keep the reward model
on-distribution and maintain an accur

==========================================================================================
RANK: 4
PAPER PAGE: 13
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume of data annotation used for training, a signal that there is
room for more improvement with more ann

In [42]:
for document in fine_tuning_documents:
    assert document.metadata["section"] == "fine_tuning"

print("All returned documents are from the fine_tuning section.")

All returned documents are from the fine_tuning section.

In [43]:
filtered_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": {
            "$and": [
                {
                    "section": {
                        "$eq": "fine_tuning"
                    }
                },
                {
                    "year": {
                        "$eq": 2023
                    }
                },
                {
                    "organization": {
                        "$eq": "Meta"
                    }
                },
            ]
        },
    }
)

In [44]:
query = "How was human preference data collected?"

filtered_documents = filtered_retriever.invoke(query)

display_documents(filtered_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
sampled human preferences, whereby human annotators select which of two model outputs they prefer.
This human feedback is subsequently used to train a reward model, which learns patterns in the preferences
of the human annotators and can then automate preference decisions.
3.2.1 Human Preference Data Collection
Next, we collect human preference data for reward modeling. We chose a binary comparison protocol over
other schemes, mainly because it enables us to maximize the diversity of collected prompts. Still, other
strategies are worth considering, which we leave for future work.
Our annotation procedure proceeds as follows. We ask annotators to first write a prompt, then choose
between two

==========================================================================================
RANK: 2
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
can be found in Section 4.2.1.
Human annotations were collected in batches on a weekly basis. As we collected more preference data, our
reward models improved, and we were able to train progressively better versions forLlama 2-Chat (see
the results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.
Since reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from
hyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to
gather new preference data using the latestLlama 2-Chat iterations. This step helps keep the reward model
on-distribution and maintain an accur

==========================================================================================
RANK: 3
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
against multiple open-source preference datasets including Anthropic Helpful and Harmless (Bai et al.,
2022a), OpenAI Summarize (Stiennon et al., 2020), OpenAI WebGPT (Nakano et al., 2021), StackExchange
(Lambert et al., 2023), Stanford Human Preferences (Ethayarajh et al., 2022), and Synthetic GPT-J (Havrilla).
We collected a large dataset of over 1 million binary comparisons based on humans applying our specified
guidelines, which we refer to asMetareward modeling data. Note that the number of tokens in prompts and
answers differs depending on the text domain. Summarization and online forum data generally have longer
prompts, while dialogue-style prompts are usually shorter. Compared to ex

==========================================================================================
RANK: 4
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
do so, we further add a margin component in the loss:
Lranking =−log(σ(rθ(x,yc)−rθ(x,yr)−m(r))) (2)
where the marginm(r) is a discrete function of the preference rating. Naturally, we use a large margin
for pairs with distinct responses, and a smaller one for those with similar responses (shown in Table 27).
We found this margin component can improve Helpfulness reward model accuracy especially on samples
where two responses are more separable. More detailed ablation and analysis can be found in Table 28 in
Appendix A.3.3.
Data Composition. We combine our newly collected data with existing open-source preference datasets
to form a larger training dataset. Initially, open-source datasets were

# Prefilter

In [46]:
pre_filter = {
    "$and": [
        {
            "section": {
                "$eq": "fine_tuning"
            }
        },
        {
            "year": {
                "$eq": 2023
            }
        },
    ]
}

pre_filtered_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4,
        "filter": pre_filter,
    }
)

pre_filtered_documents = pre_filtered_retriever.invoke(
    "How was the reward model trained?"
)


display_documents(pre_filtered_documents)

==========================================================================================
RANK: 1
PAPER PAGE: 13
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
evaluating a generative model is an open research question, the ranking task of the reward has no ambiguity.
Therefore, everything else being equal, an improvement of the reward model can be directly translated into
an improvement forLlama 2-Chat.
3.2.3 Iterative Fine-Tuning
As we received more batches of human preference data annotation, we were able to train better reward
models and collect more prompts. We therefore trained successive versions for RLHF models, referred to
here as RLHF-V1, ..., RLHF-V5.
We explored RLHF fine-tuning with two main algorithms:
• Proximal Policy Optimization (PPO)(Schulman et al., 2017), the standard in RLHF literature.
• RejectionSamplingfine-tuning . Wesampl

==========================================================================================
RANK: 2
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
Each example consists of a prompt (including previous dialogue if available) and a response, which is the
input of the reward model. We report the number of comparisons, the average number of turns per dialogue,
the average number of tokens per example, per prompt and per response. More details on Meta helpfulness
and safety data per batch can be found in Appendix A.3.1.
knows. This prevents cases where, for instance, the two models would have an information mismatch, which
could result in favoring hallucinations. The model architecture and hyper-parameters are identical to those
of the pretrained language models, except that the classification head for next-token prediction is replaced
with

==========================================================================================
RANK: 3
PAPER PAGE: 10
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
3.2.2 Reward Modeling
The reward model takes a model response and its corresponding prompt (including contexts from previous
turns) as inputs and outputs a scalar score to indicate the quality (e.g., helpfulness and safety) of the model
generation. Leveraging such response scores as rewards, we can optimizeLlama 2-Chat during RLHF for
better human preference alignment and improved helpfulness and safety.
Others have found that helpfulness and safety sometimes trade off (Bai et al., 2022a), which can make it
challenging for a single reward model to perform well on both. To address this, we train two separate reward
models, one optimized for helpfulness (referred to asHelpfulness RM) and anoth

==========================================================================================
RANK: 4
PAPER PAGE: 11
SECTION: fine_tuning
CHUNK ID: None
SOURCE: /Users/sainaveenvasa/Downloads/Agentic10PM_VScode/Data/llama2-research-paper.pdf
------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different mixing recipes for both
Helpfulness and Safety reward models to ascertain the best settings. After ex

## Post-Filtering

In [73]:
unfiltered_candidates = vector_store.similarity_search(
    query="How was the reward model trained?",
    k=15,
)

In [74]:
post_filtered_documents = [
    document
    for document in unfiltered_candidates
    if document.metadata.get("section") == "fine_tuning"
    and document.metadata.get("year") == 2023
]

display_documents(post_filtered_documents)

====================================================================================================
Retrieved Documents
====================================================================================================

RANK: 1
Paper page: 13
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
evaluating a generative model is an open research question, the ranking task of the reward has no ambiguity.
Therefore, everything else being equal, an improvement of the reward model can be directly translated into
an improvement forLlama 2-Chat.
3.2.3 Iterative Fine-Tuning
As we received more batches of human preference data annotation, we were able to train better reward
models and collect more prompts. We therefore trained successive versions for RLHF models, referred to
here as RLHF-V1, ..., RLHF-V5.
We explored RLHF fine-tuning with two main algorithms:
• Proximal Policy Optimization (PP

RANK: 2
Paper page: 11
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
Each example consists of a prompt (including previous dialogue if available) and a response, which is the
input of the reward model. We report the number of comparisons, the average number of turns per dialogue,
the average number of tokens per example, per prompt and per response. More details on Meta helpfulness
and safety data per batch can be found in Appendix A.3.1.
knows. This prevents cases where, for instance, the two models would have an information mismatch, which
could result in favoring hallucinations. The model architecture and hyper-parameters are identical to those
of the pretra

RANK: 3
Paper page: 10
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
3.2.2 Reward Modeling
The reward model takes a model response and its corresponding prompt (including contexts from previous
turns) as inputs and outputs a scalar score to indicate the quality (e.g., helpfulness and safety) of the model
generation. Leveraging such response scores as rewards, we can optimizeLlama 2-Chat during RLHF for
better human preference alignment and improved helpfulness and safety.
Others have found that helpfulness and safety sometimes trade off (Bai et al., 2022a), which can make it
challenging for a single reward model to perform well on both. To address this, we trai

RANK: 4
Paper page: 11
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
this study, the role of reward signals is to learn human preference forLlama 2-Chat outputs rather than
any modeloutputs. However, in our experiments, we do not observe negative transfer from the open-source
preference datasets. Thus, we have decided to keep them in our data mixture, as they could enable better
generalization for the reward model and prevent reward hacking, i.e.Llama 2-Chat taking advantage of
some weaknesses of our reward, and so artificially inflating the score despite performing less well.
With training data available from different sources, we experimented with different m

RANK: 5
Paper page: 10
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
against multiple open-source preference datasets including Anthropic Helpful and Harmless (Bai et al.,
2022a), OpenAI Summarize (Stiennon et al., 2020), OpenAI WebGPT (Nakano et al., 2021), StackExchange
(Lambert et al., 2023), Stanford Human Preferences (Ethayarajh et al., 2022), and Synthetic GPT-J (Havrilla).
We collected a large dataset of over 1 million binary comparisons based on humans applying our specified
guidelines, which we refer to asMetareward modeling data. Note that the number of tokens in prompts and
answers differs depending on the text domain. Summarization and online forum

RANK: 6
Paper page: 10
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
can be found in Section 4.2.1.
Human annotations were collected in batches on a weekly basis. As we collected more preference data, our
reward models improved, and we were able to train progressively better versions forLlama 2-Chat (see
the results in Section 5, Figure 20).Llama 2-Chat improvement also shifted the model’s data distribution.
Since reward model accuracy can quickly degrade if not exposed to this new sample distribution, i.e., from
hyper-specialization (Scialom et al., 2020b), it is important before a newLlama 2-Chat tuning iteration to
gather new preference data using the latest

RANK: 7
Paper page: 12
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
best on the Meta Helpfulness test set, and similarly the Safety reward model performing best on the Meta
Safety test set. Overall, our reward models outperform all of the baselines, including GPT-4. Interestingly,
GPT-4 performs better than other non-Meta reward models, despite not being trained directly nor targeting
specifically this reward modeling task.
12

RANK: 8
Paper page: 13
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
with our reward, consistent with Bai et al. (2022b). The same re-ranking strategy for LLMs was also
proposed inDeng et al. (2019), where the rewardis seen asan energy function. Here, we go onestep
further, and use the selected outputs for a gradient update. For each prompt, the sample obtaining
13

RANK: 9
Paper page: 17
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
answers based on a 7-point Likert scale (the higher the better). We observe that our reward models overall
are well calibrated with our human preference annotations, as illustrated in Figure 29 in the appendix. This
confirms the relevance of using our reward as a point-wise metric, despite being trained with a Pairwise
Ranking Loss.
Still, as Goodhart’s Law states, when a measure becomes a target, it ceases to be a good measure. To ensure
ourmeasurewon’tdivergefromthehumanpreferences,weadditionallyusedamoregeneralreward,trained
17

RANK: 10
Paper page: 10
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
sampled human preferences, whereby human annotators select which of two model outputs they prefer.
This human feedback is subsequently used to train a reward model, which learns patterns in the preferences
of the human annotators and can then automate preference decisions.
3.2.1 Human Preference Data Collection
Next, we collect human preference data for reward modeling. We chose a binary comparison protocol over
other schemes, mainly because it enables us to maximize the diversity of collected prompts. Still, other
strategies are worth considering, which we leave for future work.
Our annotatio

In [75]:
print(
    "Documents retrieved before post-filtering:",
    len(unfiltered_candidates),
)

print(
    "Documents remaining after post-filtering:",
    len(post_filtered_documents),
)

Documents retrieved before post-filtering: 15
Documents remaining after post-filtering: 13

In [76]:
import os
from typing import List

from pydantic import BaseModel, Field

from langchain_community.retrievers import BM25Retriever
from langchain_classic.retrievers.ensemble import EnsembleRetriever

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from langchain_classic.retrievers.contextual_compression import (
    ContextualCompressionRetriever,
)
from langchain_classic.retrievers.document_compressors import (
    CrossEncoderReranker,
)
from langchain_community.cross_encoders import HuggingFaceCrossEncoder

In [77]:
def display_documents(
    documents,
    title: str = "Retrieved Documents",
    max_documents: int = 10,
    max_characters: int = 600,
) -> None:
    """Display retrieved LangChain Document objects."""

    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)

    if not documents:
        print("No documents were returned.")
        return

    for rank, document in enumerate(
        documents[:max_documents],
        start=1,
    ):
        metadata = document.metadata

        print(f"\nRANK: {rank}")
        print(f"Paper page: {metadata.get('paper_page')}")
        print(f"Section: {metadata.get('section')}")
        print(f"Chunk ID: {metadata.get('chunk_id')}")
        print("-" * 100)
        print(document.page_content[:max_characters])

In [78]:
def deduplicate_documents(documents):
    """Remove duplicate retrieved chunks while preserving their order."""

    unique_documents = []
    seen_keys = set()

    for document in documents:
        key = (
            document.metadata.get("chunk_id")
            or (
                document.metadata.get("source"),
                document.metadata.get("page"),
                document.page_content,
            )
        )

        if key not in seen_keys:
            seen_keys.add(key)
            unique_documents.append(document)

    return unique_documents

In [79]:
from langchain_community.retrievers import BM25Retriever

In [80]:
bm25_retriever = BM25Retriever.from_documents(chunks)

In [81]:
bm25_retriever

BM25Retriever(vectorizer=<rank_bm25.BM25Okapi object at 0x11fd291d0>)

In [82]:
bm25_retriever.k = 4

In [83]:
sparse_query = "Grouped-Query Attention GQA 70B"

In [84]:
sparse_documents = bm25_retriever.invoke(sparse_query)

In [85]:
display_documents(
    sparse_documents,
    title="Sparse Retrieval: BM25 Results",
)

====================================================================================================
Sparse Retrieval: BM25 Results
====================================================================================================

RANK: 1
Paper page: 6
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0× 10−4
13B 2k ✗ 1.0T 3.0× 10−4
33B 2k ✗ 1.4T 1.5× 10−4
65B 2k ✗ 1.4T 1.5× 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0× 10−4
13B 4k ✗ 2.0T 3.0× 10−4
34B 4k ✓ 2.0T 1.5× 10−4
70B 4k ✓ 2.0T 1.5× 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 1500 1750

RANK: 2
Paper page: 48
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
BoolQ PIQA SIQA Hella-Swag ARC-e ARC-c NQ TQA MMLU GSM8K Human-Eval
MHA 71.0 79.3 48.2 75.1 71.2 43.0 12.4 44.7 28.0 4.9 7.9
MQA 70.6 79.0 47.9 74.5 71.6 41.9 14.5 42.8 26.5 4.8 7.3
GQA 69.4 78.8 48.6 75.4 72.1 42.5 14.0 46.2 26.9 5.3 7.9
Table 18: Attention architecture ablations.We report 0-shot results for all tasks except MMLU(5-shot) and
GSM8K(8-shot). For GSM8K and Human-Eval we report maj@1 and pass@1 results. For NQ and TriviaQA
we report EM. For all other tasks we report accuracy.
Figure 24: Multi-query variants enable higher throughput with larger batch sizes, and show similar
latenc

RANK: 3
Paper page: 47
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
attention (MHA) models grow significantly. For larger models, where KV cache size becomes a bottleneck,
key and value projections can be shared across multiple heads without much degradation of performance
(Chowdheryetal.,2022). Eithertheoriginalmulti-queryformatwithasingleKVprojection(MQA, Shazeer,
2019) or a grouped-query attention variant with 8 KV projections (GQA, Ainslie et al., 2023) can be used.
In Table 18, we compare MQA and GQA variants with an MHA baseline. We train all models with 150B
tokens while keeping a fixed 30B model size. To keep a similar overall parameter count across GQ

RANK: 4
Paper page: 48
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
memory error at a batch size of 1024 for a context of 256 tokens and at a batch size of 128 for 2k context,
whereas MQA and GQA have successful runs in those settings.
Therefore, based on the ablation results and ease of scaling inference, for the 34B and 70BLlama 2 models
we chose to use GQA instead of MQA.
Figure 24 shows how inference speed changed for the 30B GQA and MQA ablation models compared to the
MHA baseline, in an experiment using 8 x 80 GiB A100s with tensor parallelism. In these runs we simply
duplicated the KV heads for MQA in all GPUs, so the KV cache size for MQA became equal

In [86]:
dense_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 4
    },
)

In [87]:
dense_query = (
    "How did Meta improve inference scalability "
    "for the largest Llama 2 models?"
)

dense_documents = dense_retriever.invoke(dense_query)

display_documents(
    dense_documents,
    title="Dense Retrieval: Vector Search Results",
)

====================================================================================================
Dense Retrieval: Vector Search Results
====================================================================================================

RANK: 1
Paper page: 5
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
Specifically, we performed more robust data cleaning, updated our data mixes, trained on 40% more total
tokens,doubledthecontextlength,andusedgrouped-queryattention(GQA)toimproveinferencescalability
for our larger models. Table 1 compares the attributes of the newLlama 2 models with theLlama 1 models.
2.1 Pretraining Data
Our training corpus includes a new mix of data from publicly available sources, which does not include data
from Meta’s products or services. We made an effort to remove data from certain sites known to contain a
high volume of personal information about private individuals.

RANK: 2
Paper page: 77
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
Llama 2.
Hardware and Software(Section 2.2)
Training Factors We used custom training libraries, Meta’s Research Super Cluster, and produc-
tion clusters for pretraining. Fine-tuning, annotation, and evaluation were also
performed on third-party cloud compute.
Carbon Footprint Pretraining utilized a cumulative 3.3M GPU hours of computation on hardware
of type A100-80GB (TDP of 350-400W). Estimated total emissions were 539
tCO2eq, 100% of which were offset by Meta’s sustainability program.
Training Data(Sections 2.1 and 3)
Overview Llama 2 was pretrained on 2 trillion tokens of data from publicl

RANK: 3
Paper page: 3
Section: introduction
Chunk ID: None
----------------------------------------------------------------------------------------------------
the community to advance AI alignment research.
In this work, we develop and release Llama 2, a family of pretrained and fine-tuned LLMs,Llama 2 and
Llama 2-Chat, at scales up to 70B parameters. On the series of helpfulness and safety benchmarks we tested,
Llama 2-Chat models generally perform better than existing open-source models. They also appear to
be on par with some of the closed-source models, at least on the human evaluations we performed (see
Figures 1 and 3). We have taken measures to increase the safety of these models, using safety-specific data
annotation and tuning, as well as c

RANK: 4
Paper page: 48
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
memory error at a batch size of 1024 for a context of 256 tokens and at a batch size of 128 for 2k context,
whereas MQA and GQA have successful runs in those settings.
Therefore, based on the ablation results and ease of scaling inference, for the 34B and 70BLlama 2 models
we chose to use GQA instead of MQA.
Figure 24 shows how inference speed changed for the 30B GQA and MQA ablation models compared to the
MHA baseline, in an experiment using 8 x 80 GiB A100s with tensor parallelism. In these runs we simply
duplicated the KV heads for MQA in all GPUs, so the KV cache size for MQA became equal

In [88]:
comparison_query = (
    "How did grouped-query attention improve "
    "Llama 2 inference scalability?"
)

sparse_results = bm25_retriever.invoke(comparison_query)
dense_results = dense_retriever.invoke(comparison_query)

display_documents(
    sparse_results,
    title="BM25 Results",
    max_documents=4,
)

display_documents(
    dense_results,
    title="Dense Vector Results",
    max_documents=4,
)

====================================================================================================
BM25 Results
====================================================================================================

RANK: 1
Paper page: 4
Section: introduction
Chunk ID: None
----------------------------------------------------------------------------------------------------
1. Llama 2, an updated version ofLlama 1, trained on a new mix of publicly available data. We also
increased the size of the pretraining corpus by 40%, doubled the context length of the model, and
adopted grouped-query attention (Ainslie et al., 2023). We are releasing variants ofLlama 2 with
7B, 13B, and 70B parameters. We have also trained 34B variants, which we report on in this paper
but are not releasing.§
2. Llama 2-Chat, a fine-tuned version ofLlama 2 that is optimized for dialogue use cases. We release
variants of this model with 7B, 13B, and 70B parameters as well.
We believe that the

RANK: 2
Paper page: 47
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
attention (MHA) models grow significantly. For larger models, where KV cache size becomes a bottleneck,
key and value projections can be shared across multiple heads without much degradation of performance
(Chowdheryetal.,2022). Eithertheoriginalmulti-queryformatwithasingleKVprojection(MQA, Shazeer,
2019) or a grouped-query attention variant with 8 KV projections (GQA, Ainslie et al., 2023) can be used.
In Table 18, we compare MQA and GQA variants with an MHA baseline. We train all models with 150B
tokens while keeping a fixed 30B model size. To keep a similar overall parameter count across GQ

RANK: 3
Paper page: 6
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0× 10−4
13B 2k ✗ 1.0T 3.0× 10−4
33B 2k ✗ 1.4T 1.5× 10−4
65B 2k ✗ 1.4T 1.5× 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0× 10−4
13B 4k ✗ 2.0T 3.0× 10−4
34B 4k ✓ 2.0T 1.5× 10−4
70B 4k ✓ 2.0T 1.5× 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 1500 1750

RANK: 4
Paper page: 54
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
attribute, and so, up to 20 turns (we did not extend the human evaluation more, and all the examples had
less than 4048 tokens in total over the turns). As a comparison,Llama 2-Chat without GAtt can not anymore
refer to the attributes after only few turns: from 100% at turn t+1, to 10% at turn t+3 and then 0%.
GAtt Zero-shot Generalisation. We tried at inference time to set constrain not present in the training of
GAtt. For instance, “answer in one sentence only”, for which the model remained consistent, as illustrated in
Figure 28.
We applied first GAtt toLlama 1, which was pretrained with a

====================================================================================================
Dense Vector Results
====================================================================================================

RANK: 1
Paper page: 13
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume

RANK: 2
Paper page: 48
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
memory error at a batch size of 1024 for a context of 256 tokens and at a batch size of 128 for 2k context,
whereas MQA and GQA have successful runs in those settings.
Therefore, based on the ablation results and ease of scaling inference, for the 34B and 70BLlama 2 models
we chose to use GQA instead of MQA.
Figure 24 shows how inference speed changed for the 30B GQA and MQA ablation models compared to the
MHA baseline, in an experiment using 8 x 80 GiB A100s with tensor parallelism. In these runs we simply
duplicated the KV heads for MQA in all GPUs, so the KV cache size for MQA became equal

RANK: 3
Paper page: 5
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
Specifically, we performed more robust data cleaning, updated our data mixes, trained on 40% more total
tokens,doubledthecontextlength,andusedgrouped-queryattention(GQA)toimproveinferencescalability
for our larger models. Table 1 compares the attributes of the newLlama 2 models with theLlama 1 models.
2.1 Pretraining Data
Our training corpus includes a new mix of data from publicly available sources, which does not include data
from Meta’s products or services. We made an effort to remove data from certain sites known to contain a
high volume of personal information about private individuals.

RANK: 4
Paper page: 6
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0× 10−4
13B 2k ✗ 1.0T 3.0× 10−4
33B 2k ✗ 1.4T 1.5× 10−4
65B 2k ✗ 1.4T 1.5× 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0× 10−4
13B 4k ✗ 2.0T 3.0× 10−4
34B 4k ✓ 2.0T 1.5× 10−4
70B 4k ✓ 2.0T 1.5× 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 1500 1750

In [89]:
print("SPARSE RESULTS")
for rank, document in enumerate(sparse_results, start=1):
    print(
        rank,
        document.metadata.get("paper_page"),
        document.metadata.get("chunk_id"),
    )

print("\nDENSE RESULTS")
for rank, document in enumerate(dense_results, start=1):
    print(
        rank,
        document.metadata.get("paper_page"),
        document.metadata.get("chunk_id"),
    )

SPARSE RESULTS
1 4 None
2 47 None
3 6 None
4 54 None

DENSE RESULTS
1 13 None
2 48 None
3 5 None
4 6 None

In [90]:
bm25_retriever.k = 8

dense_retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 8
    },
)

In [91]:
from langchain_classic.retrievers.ensemble import EnsembleRetriever

In [92]:
hybrid_retriever=EnsembleRetriever(
    retrievers=[bm25_retriever, dense_retriever],
    weights=[0.5, 0.5] # BM25 weight, # Dense-retrieval weight 
)

In [93]:
hybrid_query = (
    "Llama 2 70B grouped-query attention and inference scalability"
)

In [94]:
hybrid_results=hybrid_retriever.invoke(hybrid_query)

In [95]:
display_documents(
    hybrid_results,
    title="Hybrid Retrieval: BM25 + Dense + RRF (0.5, 0.5)  Reciprocal Rank Fusion",
    max_documents=6,
)

====================================================================================================
Hybrid Retrieval: BM25 + Dense + RRF (0.5, 0.5)  Reciprocal Rank Fusion
====================================================================================================

RANK: 1
Paper page: 4
Section: introduction
Chunk ID: None
----------------------------------------------------------------------------------------------------
1. Llama 2, an updated version ofLlama 1, trained on a new mix of publicly available data. We also
increased the size of the pretraining corpus by 40%, doubled the context length of the model, and
adopted grouped-query attention (Ainslie et al., 2023). We are releasing variants ofLlama 2 with
7B, 13B, and 70B parameters. We have also trained 34B variants, which we report on in this paper
but are not releasing.§
2. Llama 2-Chat, a fine-tuned version ofLlama 2 that is optimized for dialogue use cases. We release
variants of this model with 7B, 13B, and 70B parameters as well.
We believe that the

RANK: 2
Paper page: 6
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0× 10−4
13B 2k ✗ 1.0T 3.0× 10−4
33B 2k ✗ 1.4T 1.5× 10−4
65B 2k ✗ 1.4T 1.5× 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0× 10−4
13B 4k ✗ 2.0T 3.0× 10−4
34B 4k ✓ 2.0T 1.5× 10−4
70B 4k ✓ 2.0T 1.5× 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 1500 1750

RANK: 3
Paper page: 8
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
• Popular Aggregated Benchmarks. We report the overall results for MMLU (5 shot) (Hendrycks
et al., 2020), Big Bench Hard (BBH) (3 shot) (Suzgun et al., 2022), and AGI Eval (3–5 shot) (Zhong
et al., 2023). For AGI Eval, we only evaluate on the English tasks and report the average.
As shown in Table 3,Llama 2 models outperformLlama 1 models. In particular,Llama 2 70B improves the
resultsonMMLUandBBHby ≈5and≈8points, respectively, comparedtoLlama 1 65B. Llama 2 7Band30B
modelsoutperformMPTmodelsofthecorrespondingsizeonallcategoriesbesidescodebenchmarks. Forthe
Falcon models,Llama 2 7B and 34B ou

RANK: 4
Paper page: 47
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
attention (MHA) models grow significantly. For larger models, where KV cache size becomes a bottleneck,
key and value projections can be shared across multiple heads without much degradation of performance
(Chowdheryetal.,2022). Eithertheoriginalmulti-queryformatwithasingleKVprojection(MQA, Shazeer,
2019) or a grouped-query attention variant with 8 KV projections (GQA, Ainslie et al., 2023) can be used.
In Table 18, we compare MQA and GQA variants with an MHA baseline. We train all models with 150B
tokens while keeping a fixed 30B model size. To keep a similar overall parameter count across GQ

RANK: 5
Paper page: 5
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
We performed a variety of pretraining data investigations so that users can better understand the potential
capabilities and limitations of our models; results can be found in Section 4.1.
2.2 Training Details
We adopt most of the pretraining setting and model architecture fromLlama 1. We use the standard
transformer architecture (Vaswani et al., 2017), apply pre-normalization using RMSNorm (Zhang and
Sennrich, 2019), use the SwiGLU activation function (Shazeer, 2020), and rotary positional embeddings
(RoPE, Su et al. 2022). The primary architectural differences fromLlama 1 include increased c

RANK: 6
Paper page: 13
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
mosttoimprove Llama 2-Chatperformance. Thehumanpreferenceannotationagreementrateisalsohigher
on more distinct responses than similar pairs.
Scaling Trends. We study the scaling trends in terms of data and model size for the reward model, fine-
tuning different model sizes on an increasing amount of the reward model data collected each week (see the
detailsonvolumeperbatchinTable26). Figure6reportsthesetrends,showingtheexpectedresultthatlarger
models obtain higher performance for a similar volume of data. More importantly, the scaling performance
has not yet plateaued given the existing volume

                        ┌── BM25 Retriever ─────┐
User query ──────────────┤                       ├── Weighted RRF
                         └── Dense Retriever ────┘
                                                    ↓
                                            Combined ranking

In [96]:
test_query = (
    "How did Meta make Llama 2 70B efficient for large-scale inference?"
)

In [97]:
sparse_results = bm25_retriever.invoke(test_query)
dense_results = dense_retriever.invoke(test_query)
hybrid_results = hybrid_retriever.invoke(test_query)

In [98]:
display_documents(
    sparse_results,
    title="1. Sparse Retrieval",
    max_documents=4,
)

display_documents(
    dense_results,
    title="2. Dense Retrieval",
    max_documents=4,
)

display_documents(
    hybrid_results,
    title="3. Hybrid Retrieval",
    max_documents=4,
)

====================================================================================================
1. Sparse Retrieval
====================================================================================================

RANK: 1
Paper page: 54
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
attribute, and so, up to 20 turns (we did not extend the human evaluation more, and all the examples had
less than 4048 tokens in total over the turns). As a comparison,Llama 2-Chat without GAtt can not anymore
refer to the attributes after only few turns: from 100% at turn t+1, to 10% at turn t+3 and then 0%.
GAtt Zero-shot Generalisation. We tried at inference time to set constrain not present in the training of
GAtt. For instance, “answer in one sentence only”, for which the model remained consistent, as illustrated in
Figure 28.
We applied first GAtt toLlama 1, which was pretrained with a

RANK: 2
Paper page: 6
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0× 10−4
13B 2k ✗ 1.0T 3.0× 10−4
33B 2k ✗ 1.4T 1.5× 10−4
65B 2k ✗ 1.4T 1.5× 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0× 10−4
13B 4k ✗ 2.0T 3.0× 10−4
34B 4k ✓ 2.0T 1.5× 10−4
70B 4k ✓ 2.0T 1.5× 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 1500 1750

RANK: 3
Paper page: 51
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
Model Size GSM8k MATH
MPT 7B 6.8 3.0
30B 15.2 3.1
Falcon 7B 6.8 2.3
40B 19.6 5.5
Llama 1
7B 11.0 2.9
13B 17.8 3.9
33B 35.6 7.1
65B 50.9 10.6
Llama 2
7B 14.6 2.5
13B 28.7 3.9
34B 42.2 6.24
70B 56.8 13.5
Table 25: Comparison to other open-source models on mathematical reasoning tasks, GSM8k and MATH
(maj1@1 is reported).
Mathematical Reasoning. In Table 25, we report results forLlama 2 and other open-source datasets on the
GSM8k and MATH tasks.
A.3 Additional Details for Fine-tuning
A.3.1 Detailed Statistics of Meta Human Preference Data
Table 26 shows detailed statistics on Meta human preferenc

RANK: 4
Paper page: 54
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
adapted as an efficient technique for long context attention.
A.3.6 How Far Can Model-Based Evaluation Go?
To measure the robustness of our reward model, we collected a test set of prompts for both helpfulness and
safety, and asked annotators to judge quality of the answers based on a 7 point Likert-scale (the higher the
better) using triple reviews. As illustrated in Figure 29 (in Appendix), we observe that our reward models
overallarewellcalibratedwithhumanpreference. Notethatthisenablesustousetherewardasapoint-wise
metric, despite being trained with a Pairwise Ranking Loss.
0.0% 2.0% 4.0% 6

====================================================================================================
2. Dense Retrieval
====================================================================================================

RANK: 1
Paper page: 77
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
Llama 2.
Hardware and Software(Section 2.2)
Training Factors We used custom training libraries, Meta’s Research Super Cluster, and produc-
tion clusters for pretraining. Fine-tuning, annotation, and evaluation were also
performed on third-party cloud compute.
Carbon Footprint Pretraining utilized a cumulative 3.3M GPU hours of computation on hardware
of type A100-80GB (TDP of 350-400W). Estimated total emissions were 539
tCO2eq, 100% of which were offset by Meta’s sustainability program.
Training Data(Sections 2.1 and 3)
Overview Llama 2 was pretrained on 2 trillion tokens of data from publicl

RANK: 2
Paper page: 5
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
Specifically, we performed more robust data cleaning, updated our data mixes, trained on 40% more total
tokens,doubledthecontextlength,andusedgrouped-queryattention(GQA)toimproveinferencescalability
for our larger models. Table 1 compares the attributes of the newLlama 2 models with theLlama 1 models.
2.1 Pretraining Data
Our training corpus includes a new mix of data from publicly available sources, which does not include data
from Meta’s products or services. We made an effort to remove data from certain sites known to contain a
high volume of personal information about private individuals.

RANK: 3
Paper page: 3
Section: introduction
Chunk ID: None
----------------------------------------------------------------------------------------------------
Feedback (RLHF). Although the training methodology is simple, high computational requirements have
limited the development of LLMs to a few players. There have been public releases of pretrained LLMs
(such as BLOOM (Scao et al., 2022), LLaMa-1 (Touvron et al., 2023), and Falcon (Penedo et al., 2023)) that
match the performance of closed pretrained competitors like GPT-3 (Brown et al., 2020) and Chinchilla
(Hoffmann et al., 2022), but none of these models are suitable substitutes for closed “product” LLMs, such
as ChatGPT, BARD, and Claude. These closed product LLMs are heavily fine-tuned to al

RANK: 4
Paper page: 4
Section: introduction
Chunk ID: None
----------------------------------------------------------------------------------------------------
1. Llama 2, an updated version ofLlama 1, trained on a new mix of publicly available data. We also
increased the size of the pretraining corpus by 40%, doubled the context length of the model, and
adopted grouped-query attention (Ainslie et al., 2023). We are releasing variants ofLlama 2 with
7B, 13B, and 70B parameters. We have also trained 34B variants, which we report on in this paper
but are not releasing.§
2. Llama 2-Chat, a fine-tuned version ofLlama 2 that is optimized for dialogue use cases. We release
variants of this model with 7B, 13B, and 70B parameters as well.
We believe that the

====================================================================================================
3. Hybrid Retrieval
====================================================================================================

RANK: 1
Paper page: 6
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
Training Data Params Context
Length
GQA Tokens LR
Llama 1 See Touvron et al.
(2023)
7B 2k ✗ 1.0T 3.0× 10−4
13B 2k ✗ 1.0T 3.0× 10−4
33B 2k ✗ 1.4T 1.5× 10−4
65B 2k ✗ 1.4T 1.5× 10−4
Llama 2 A new mix of publicly
available online data
7B 4k ✗ 2.0T 3.0× 10−4
13B 4k ✗ 2.0T 3.0× 10−4
34B 4k ✓ 2.0T 1.5× 10−4
70B 4k ✓ 2.0T 1.5× 10−4
Table 1:Llama 2 family of models.Token counts refer to pretraining data only. All models are trained with
a global batch-size of 4M tokens. Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for
improved inference scalability.
0 250 500 750 1000 1250 1500 1750

RANK: 2
Paper page: 8
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
• Popular Aggregated Benchmarks. We report the overall results for MMLU (5 shot) (Hendrycks
et al., 2020), Big Bench Hard (BBH) (3 shot) (Suzgun et al., 2022), and AGI Eval (3–5 shot) (Zhong
et al., 2023). For AGI Eval, we only evaluate on the English tasks and report the average.
As shown in Table 3,Llama 2 models outperformLlama 1 models. In particular,Llama 2 70B improves the
resultsonMMLUandBBHby ≈5and≈8points, respectively, comparedtoLlama 1 65B. Llama 2 7Band30B
modelsoutperformMPTmodelsofthecorrespondingsizeonallcategoriesbesidescodebenchmarks. Forthe
Falcon models,Llama 2 7B and 34B ou

RANK: 3
Paper page: 54
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
attribute, and so, up to 20 turns (we did not extend the human evaluation more, and all the examples had
less than 4048 tokens in total over the turns). As a comparison,Llama 2-Chat without GAtt can not anymore
refer to the attributes after only few turns: from 100% at turn t+1, to 10% at turn t+3 and then 0%.
GAtt Zero-shot Generalisation. We tried at inference time to set constrain not present in the training of
GAtt. For instance, “answer in one sentence only”, for which the model remained consistent, as illustrated in
Figure 28.
We applied first GAtt toLlama 1, which was pretrained with a

RANK: 4
Paper page: 77
Section: appendix
Chunk ID: None
----------------------------------------------------------------------------------------------------
Llama 2.
Hardware and Software(Section 2.2)
Training Factors We used custom training libraries, Meta’s Research Super Cluster, and produc-
tion clusters for pretraining. Fine-tuning, annotation, and evaluation were also
performed on third-party cloud compute.
Carbon Footprint Pretraining utilized a cumulative 3.3M GPU hours of computation on hardware
of type A100-80GB (TDP of 350-400W). Estimated total emissions were 539
tCO2eq, 100% of which were offset by Meta’s sustainability program.
Training Data(Sections 2.1 and 3)
Overview Llama 2 was pretrained on 2 trillion tokens of data from publicl

# Query Transformation

In [99]:
CHAT_MODEL = os.environ.get(
    "OPENAI_CHAT_MODEL",
    "gpt-4.1-mini",
)

llm = ChatOpenAI(
    model=CHAT_MODEL,
    temperature=0,
)

print("Chat model:", CHAT_MODEL)

Chat model: gpt-4.1-mini

In [100]:
query_rewriting_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
You rewrite conversational questions into clear,
standalone search queries.

Rules:
1. Do not answer the question.
2. Preserve important entities, dates, and technical terms.
3. Resolve pronouns using the conversation history.
4. Return only one rewritten query.
""",
        ),
        (
            "human",
            """
Conversation history:
{chat_history}

Current query:
{query}
""",
        ),
    ]
)

In [101]:
query_rewriting_chain = (query_rewriting_prompt| llm | StrOutputParser())

In [102]:
chat_history = """
User: How was Llama 2-Chat initially fine-tuned?
Assistant: It first underwent supervised fine-tuning.
"""

In [103]:
original_query = "What did Meta do after that?"

In [104]:
rewritten_query = query_rewriting_chain.invoke(
    {
        "chat_history": chat_history,
        "query": original_query,
    }
).strip()

In [105]:
print("Original query:")
print(original_query)

print("\nRewritten query:")
print(rewritten_query)

Original query:
What did Meta do after that?

Rewritten query:
What steps did Meta take after the initial supervised fine-tuning of Llama 2-Chat?

In [106]:
rewritten_query_documents = hybrid_retriever.invoke(
    rewritten_query
)

In [107]:
display_documents(
    rewritten_query_documents,
    title="Documents Retrieved Using the Rewritten Query",
    max_documents=5,
)

====================================================================================================
Documents Retrieved Using the Rewritten Query
====================================================================================================

RANK: 1
Paper page: 8
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
are from OpenAI (2023). Results for the PaLM model are from Chowdhery et al. (2022). Results for the
PaLM-2-L are from Anil et al. (2023).
3 Fine-tuning
Llama 2-Chat is the result of several months of research and iterative applications of alignment techniques,
including both instruction tuning and RLHF, requiring significant computational and annotation resources.
In this section, we report on our experiments and findings using supervised fine-tuning (Section 3.1), as
well as initial and iterative reward modeling (Section 3.2.2) and RLHF (Section 3.2.3). We also share a
new technique, Ghost A

RANK: 2
Paper page: 5
Section: pretraining
Chunk ID: None
----------------------------------------------------------------------------------------------------
Figure 4: Training ofLlama 2-Chat: This process begins with thepretraining of Llama 2 using publicly
available online sources. Following this, we create an initial version ofLlama 2-Chatthrough the application
of supervised fine-tuning. Subsequently, the model is iteratively refined using Reinforcement Learning
with Human Feedback(RLHF) methodologies, specifically through rejection sampling and Proximal Policy
Optimization (PPO). Throughout the RLHF stage, the accumulation ofiterative reward modeling datain
parallel with model enhancements is crucial to ensure the reward models remain within d

RANK: 3
Paper page: 16
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
or to“act as”some public figure. When we provided such instructions toLlama 2-Chat, the subsequent
response should always respect the constraint. However, our initial RLHF models tended to forget the initial
instruction after a few turns of dialogue, as illustrated in Figure 9 (left).
To address these limitations, we propose Ghost Attention (GAtt), a very simple method inspired by Context
Distillation (Bai et al., 2022b) that hacks the fine-tuning data to help the attention focus in a multi-stage
process. GAtt enables dialogue control over multiple turns, as illustrated in Figure 9 (right).
GA

RANK: 4
Paper page: 9
Section: fine_tuning
Chunk ID: None
----------------------------------------------------------------------------------------------------
27,540 annotations. Note that we do not include any Meta user data.
We also observed that different annotation platforms and vendors can result in markedly different down-
stream model performance, highlighting the importance of data checks even when using vendors to source
annotations. Tovalidateourdataquality,wecarefullyexaminedasetof180examples,comparingtheannota-
tions provided by humans with the samples generated by the model through manual scrutiny. Surprisingly,
we found that the outputs sampled from the resulting SFT model were often competitive with SFT data
handwritten by human annot

RANK: 5
Paper page: 4
Section: introduction
Chunk ID: None
----------------------------------------------------------------------------------------------------
Solaiman et al., 2023). Testing conducted to date has been in English and has not — and could not — cover
all scenarios. Therefore, before deploying any applications ofLlama 2-Chat, developers should perform
safety testing and tuning tailored to their specific applications of the model. We provide a responsible use
guide¶ and code examples‖ to facilitate the safe deployment ofLlama 2 and Llama 2-Chat. More details of
our responsible release strategy can be found in Section 5.3.
The remainder of this paper describes our pretraining methodology (Section 2), fine-tuning methodology
(Section 3), a